### ISSUE TITLE
Class Size Prediction Algorithim

### ISSUE THREAD

**Issue by stefan-esquivel** [SENG499-COMPANY4/Algorithm-2#11]

**Comment by D-Aldana** [comment]
- https://app.swaggerhub.com/apis/seng_499_api/BackendApi/1.0.2

**Comment by D-Aldana** [comment]
First iteration for one class is completed

**Comment by D-Aldana** [comment]
One class currently takes about 2-3 seconds

**Comment by D-Aldana** [comment]
Integration and further iterations will be done in future sprints
