### ISSUE TITLE
Test Error Responses

### ISSUE THREAD

**Issue by stefan-esquivel** [SENG499-COMPANY4/Algorithm-2#34]

**Comment by ketdougi** [comment]
Error codes that were tested:
- 404: URL Not Found (test_get_to_wrong_url, test_post_to_wrong_URL)
- 405: Method not allowed (test_get)
- 415: Unsupported Media Type (test_post_no_json_file, test_post_None_json_file)
- 500: Internal Error (test_post_incorrect_file_not_list, test_post_incorrect)
