### ISSUE TITLE
Set Up Github actions CI/CD

### ISSUE THREAD

**Issue by stefan-esquivel** [SENG499-COMPANY4/Algorithm-2#5]

**Comment by ketdougi** [comment]
Added algorithm2-ci.YAML file to .github/workflows/ directory to set up CI using github actions. CI process is triggered on pushes to any branch and pull requests to master. The workflow sets up python, installs dependencies, builds and runs docker image.

**Comment by ketdougi** [comment]
Workflow successfully executed after push but shows warning: 

`[build](https://github.com/SENG499-COMPANY4/Algorithm-2/actions/runs/5139700211/jobs/9250423106)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.`
